.TH SR_PORTAL_GRANT 1 "JANUARY 2012" "SR Router" "Management Utilities"
.SH NAME 
sr_portal_grant \- Show the status of a MAC on the portal
.SH SYNOPSIS
.B sr_portal_grant 
.I mac
.I access-rule
.SH DESCRIPTION
Grants
.I mac
access to areas of the network by various access rules.  The default
access rules available are:
.IP staff
Currently does nothing.
.IP compnet
Access to the competition control network.
.IP internet
Access to the internet.
.IP management
Access to the management VLAN.
.IP video
Access to the video VLAN. 
.SH OPTIONS
.IP mac
The MAC address to look up in the policy tables.
.IP access-rule
The access to permit this MAC address.  This must be one of the above
values.
.SH AUTHOR
Chris Malton <cmalton at studentrobotics dot org>
.SH SEE ALSO
.BR iptables (8)
